name: easypayamak
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'







dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  iconly: ^1.0.1
  ionicons: ^0.2.2
  http: ^1.0.0
  flutter_svg: ^2.0.6
  figma_squircle: ^0.5.3

  smooth_widgets:
    path: /Users/omidshabab/Documents/GitHub/smooth_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  fonts:
    # PERSIAN
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad/Estedad-Thin.ttf
          weight: 100
        - asset: assets/fonts/Estedad/Estedad-Light.ttf
          weight: 200
        - asset: assets/fonts/Estedad/Estedad-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Estedad/Estedad-Regular.ttf
          weight: 400
        - asset: assets/fonts/Estedad/Estedad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad/Estedad-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Estedad/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad/Estedad-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Estedad/Estedad-Black.ttf
          weight: 900

    - family: Rokh
      fonts:
        - asset: assets/fonts/Rokh/RokhFaNum-Light.ttf
          weight: 200
        - asset: assets/fonts/Rokh/RokhFaNum-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rokh/RokhFaNum-Bold.ttf
          weight: 700


  assets:
    - lib/.env # path to your .env
    - assets/fonts/
    - assets/svg/
    - assets/images/
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
